export const skills = {
  Languages: ["Javascript", "Typescript", "SQL", "Python", "Solidity"],
  "State Management Libraries": ["Redux.js", "Zustand.js"],
  "IAC Tools": ["AWS CDK", "Terraform", "SST", "PULUMI"],
  "Version Control and Deployment": [
    "Version Control with Git",
    "CI/CD pipelines",
    "GitHub Actions",
    "Gitflow",
    "AWS",
    "Google Cloud Run",
  ],
  "JavaScript Libraries and Frameworks": [
    "React.js",
    "Next.js",
    "React Native",
  ],
  Databases: ["MySQL", "MongoDB", "Redis Cache", "Postgres", "DynamoDB", "RDS"],
  "Styling and Animation": [
    "Styled Components",
    "SCSS",
    "Tailwind CSS",
    "Framer Motion",
    "GSAP",
    "CSS Modules",
  ],
  "API Management": ["GraphQL", "Axios", "Fetch", "SWR"],
  "Graphics and Animation": ["Three.js"],
  "Server-side Frameworks": ["Express.js", "Nest.js", "Strapi.js"],
  "Web Technologies and Standards": [
    "HTTP",
    "Responsive Design Principles",
    "Localization and Internationalization (i18n)",
    "Analytics Implementation",
    "RESTful API design principles",
  ],

  "Design and Collaboration Tools": ["Figma", "Adobe Illustator"],
};

export const workHistory = [
  {
    companyName: "Rototip",
    title: "Full Stack Software Engineer",
    details: [
      "Provisioned and managed cloud infrastructure using IaC tools such as Pulumi & AWS Cloud Development Kit (CDK).",
      "Conducted Proof of Concept (POC).",
      "Utilized Nest.js to develop backend APIs and resolve existing issues.",
      "Built user interfaces with React.js and Next.js and TypeScript to create a dynamic and responsive experience for users.",
      "Transitioned the existing monorepo to a new structure using NX, optimizing code organization and build processes.",
      "Developed and maintained CI/CD pipelines using GitHub Actions.",
      "Leveraged AWS products and services, including S3, RDS Postgres, Lambda, IAM, and VPC.",
    ],
  },
  {
    companyName: "Le Polish Bureau",
    title: "Frontend Developer",
    details: [
      "Developed projects using the SCRUM methodology.",
      "Contributed to the codebase using Git and Gitflow.",
      "Written Unit tests.",
      "Used Docker throughout the development processes.",
      "Implemented classes following Object-Oriented Programming (OOP) principles.",
      "Developed backend applications with Nest.js and Express.js, and deployed them using Google Cloud services. (KPI Activity)",
      "Studied AWS (KPI Activity).",
      "Worked with Bitbucket pipelines.",
      "Managed state using various solutions such as React Context, Redux, and Zustand.",
      "Translated designs into reusable, responsive components.",
      "Wrote React applications with Next.js.",
      "Heavily used TypeScript for type safety.",
      "Used Bitbucket to collaborate with team.",
      "Styled the components using styled-components, focusing on SCSS.",
      "Implemented complex UI animations using framer-motion.",
      "Utilized React hooks to handle various lifecycle events.",
      "Implemented Google and Adobe analytics.",
      "Wrote custom hooks for improved code readability and logic isolation.",
      "Utilized various Web APIs as well as third-party integrations.",
      "Employed GraphQL writing complex queries for data fetching and i18n.",
      "Wrote WebGL code using Three.js.",
      "Used PlayCanvas as an HTML5 game engine for creating immersive experiences.",
      "Set up routes for handling user input on the backend.",
      "Debugged code.",
      "Used Strapi to build and manage APIs for content management and administration.",
    ],
  },
];

export const detailParagraphs = [
  "Hello, thank you for checking my portfolio out. I hope you've been enjoying it (and fingers crossed impressed by it). Please let me briefly introduce myself and give you a little professional background summary. I am Berat, a former Web / Graphic Designer transitioned into a Developer.",
  "Throughout my software engineering career, I've been involved in various productions, ranging from immersive web experiences to mobile applications, where I've developed complex styled applications with intricate underlying logic using Scrum Methodologies. TypeScript has been the primary programming language in these applications.",
  "I have used many popular modern libraries, frameworks and tools such as Next.js, React & React Native ecosystem, Redux, Graphql, styled-components, Tailwindcss, Node.js, Nest.js, Terraform, AWS Cloud, GCP and many more...",
  "I've started my career as a Frontend Developer and as user interface development became natural, I sought to explore more challenging and unfamiliar realms of software development. This led me to delve into Backend and DevOps technologies to understand how applications handle data and are deployed to end-users.",
  "And with that I transitioned to a more cloud focused FullStack position wehere I had the chance write API's, deploy and provision infrastructure and have the exposure to the other side of the coin.",
  "I am always out searching for new challenges and I always accept them as opportunities to grow. My interest in learning new things drives me to constantly push boundaries and tackle new challenges, which I believe is fundamental in our field.",
  "I've recently moved from Turkey to Poland with the help of my previous company. I like having walks on beautiful parks, going to the gym, discover new music and of course eating some delicious food (any kind would do to be honest). I really like being a student of the life, getting work done in my professional life, collaborate & connect with people.",
];

export const educationConfig = [
  {
    school: "Istanbul Bilgi University",
    degree: "Communication And Design Management",
    type: "Bachelors Degree",
    year: "2021-2023",
  },
  {
    school: "Istanbul Bilgi University",
    degree: "Printing & Publishing Technologies",
    type: "Associate Degree",
    year: "2019 - 2021",
  },
  {
    school: "University of Michigan",
    degree: "Interactivity with JavaScript",
    type: "Certification",
    year: "2023",
  },
  {
    school: "Meta",
    degree: "Programming with JavaScript",
    type: "Certification",
    year: "2023",
  },
  {
    school: "freeCodeCamp",
    degree: "Responsive Web Design",
    type: "Certification",
    year: "2023",
  },
  {
    school: "Encode Club X BNB Chain",
    degree: "Web3 & Solidity Bootcamp",
    type: "Certification",
    year: "2023",
  },
  {
    school: "Udemy",
    degree: "The Modern Javascript Bootcamp",
    type: "Certification",
    year: "2021",
  },
];
