import "./globals.css";
import type { Metadata } from "next";
import { M_PLUS_Code_Latin } from "next/font/google";

const mPlus = M_PLUS_Code_Latin({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg" />
        <title>Berat Genç | Portfolio</title>
      </head>
      <body className={mPlus.className}>{children}</body>
    </html>
  );
}
